spring:
  datasource:
    url: jdbc:mysql://192.168.1.200:3306/recruitment?serverTimezone=UTC
    username: root
    password: lilishop

    druid:
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false
      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 2000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  redis:
#    client-type: jedis
    host: 192.168.1.200
    port: 6379
    password: lilishop

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

kaptcha:
  height: 36
  width: 110
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ23456789
    space: 2
  font:
    color: red
    name: Arial
    size: 30
  background-color:
    from: lightGray
    to: white
  border:
    enabled: false


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging.level.com.iurac.springbootshiro01.mapper: debug